INSERT INTO chats (uuid, user_id_1, user_id_2)
VALUES ('2586ead4-20d8-40cd-9310-64f75c26a18e', 1, 2);

INSERT INTO messages (chat_id, user_id_from, content) VALUES
(1, 2, 'How do you… how do you like my lawn club for St. Lou?'),
(1, 1, 'Hey, all those people gonna be at the game today?'),
(1, 2, 'Certainly'),
(1, 1, 'Ah, this is gonna be a whopper of a game!'),
(1, 2, 'Well it should be'),
(1, 1, 'Hey, 1…'),
(1, 2, 'What?'),
(1, 1, 'I understand they made you the manager of this here whole great team'),
(1, 2, 'Why not?'),
(1, 1, 'So, you the manager?'),
(1, 2, 'I''m the manager!'),
(1, 1, 'Well, you know, I''d like to know some of the guys'' names on the team so when I meet ''em on the street or in the ballpark I''ll be able to say, "Hello" to those people'),
(1, 2, 'Why sure I''ll introduce you to the boys. They give ''em funny names though'),
(1, 1, 'Oh I know they give those ball players awful funny names'),
(1, 2, 'Well, let''s see, on the team we have uh Who''s on first, What''s on second, I Don''t Know is on third…'),
(1, 1, 'Are you the manager?'),
(1, 2, 'Yes'),
(1, 1, 'You know the guys'' names?'),
(1, 2, 'I sure do'),
(1, 1, 'Then tell me the guys'' names'),
(1, 2, 'I say, Who''s on first, What''s on second, I Don''t Know''s on third and then you…'),
(1, 1, 'You the manager?'),
(1, 2, 'Yes'),
(1, 1, 'You know the guys'' names?'),
(1, 2, 'I''m telling you their names!'),
(1, 1, 'Well who''s on first?'),
(1, 2, 'Yeah'),
(1, 1, 'Go ahead and tell me'),
(1, 2, 'Who'),
(1, 1, 'The guy on first'),
(1, 2, 'Who'),
(1, 1, 'The guy playin'' first base'),
(1, 2, 'Who'),
(1, 1, 'The guy on first'),
(1, 2, 'Who is on first!'),
(1, 1, 'What are you askin'' me for? I''m askin'' you!'),
(1, 2, 'I''m not asking you, I''m telling you'),
(1, 1, 'You ain''t tellin'' me nothin''. I''m askin'' you, who''s on first?'),
(1, 2, 'That''s it!'),
(1, 1, 'Well go ahead and tell me!'),
(1, 2, 'Who!'),
(1, 1, 'The guy on first base'),
(1, 2, 'That''s his name'),
(1, 1, 'That''s whose name?'),
(1, 2, 'Yes'),
(1, 1, 'Well go ahead and tell me'),
(1, 2, 'That''s the man''s name!'),
(1, 1, 'That''s whose name?'),
(1, 2, 'Yeah!'),
(1, 1, 'Well go ahead and tell me!'),
(1, 2, 'Who is on first'),
(1, 1, 'What are you askin'' me for? I''m askin'' you, who''s on first?'),
(1, 2, 'That''s it'),
(1, 1, 'Well go ahead and tell me'),
(1, 2, 'Who'),
(1, 1, 'The guy on first'),
(1, 2, 'That''s it'),
(1, 1, 'What''s the guy''s name on first?'),
(1, 2, 'No, What''s on second'),
(1, 1, 'I''m not askin'' you who''s on second!'),
(1, 2, 'Who''s on first'),
(1, 1, 'That''s what I''m askin'' you! Who''s on first?'),
(1, 2, 'Now wait a minute. Don''t…don''t change the players'),
(1, 1, 'I''m not changin'' nobody! I asked you a simple question. What''s the guys'' name on first base?'),
(1, 2, 'What''s the guy''s name on second base'),
(1, 1, 'I''m not askin'' you who''s on second!'),
(1, 2, 'Who''s on first'),
(1, 1, 'I don''t know'),
(1, 2, 'He''s on third. Now we''re not talking about him'),
(1, 1, 'Look, you got a first baseman?'),
(1, 2, 'Yes'),
(1, 1, 'Then tell me the fella''s name playin'' first'),
(1, 2, 'Who'),
(1, 1, 'The guy playin'' first'),
(1, 2, 'That''s his name'),
(1, 1, 'Wait…What''s the guy''s name on first base?'),
(1, 2, 'What is the guy''s name on second base!'),
(1, 1, 'Who''s playin'' second?'),
(1, 2, 'Who''s playin'' first'),
(1, 1, 'I don''t know'),
(1, 2, 'He''s on third base'),
(1, 1, 'Look, when you pay off the first baseman every month, who do you pay the money to?'),
(1, 2, 'Every dollar of it'),
(1, 1, 'Yeah. Look, you gotta pay the money to somebody on first base, don''t you?'),
(1, 2, 'Yeah'),
(1, 1, 'Does he give you a receipt?'),
(1, 2, 'Sure'),
(1, 1, 'How does he sign the receipt?'),
(1, 2, 'Who'),
(1, 1, 'The guy that you give the money to'),
(1, 2, 'Who'),
(1, 1, 'The guy you give the money to'),
(1, 2, 'That''s how he signs it'),
(1, 1, 'That''s how who signs it?'),
(1, 2, 'Yes'),
(1, 1, 'Well go ahead and tell me!?'),
(1, 2, 'That''s it'),
(1, 1, 'That''s who?'),
(1, 2, 'Yeah'),
(1, 1, 'When you give the guy the money, doesn''t he have to sign the receipt?'),
(1, 2, 'He does!'),
(1, 1, 'Well how does he sign his name?'),
(1, 2, 'Who'),
(1, 1, 'The guy you give the money to'),
(1, 2, 'That''s how he signs it!'),
(1, 1, 'You! You…You just don''t give money to someone without having ''em sign the receipt!'),
(1, 2, 'No! Who signs it'),
(1, 1, 'What are you askin'' me for?'),
(1, 2, 'Now calm down. I''m not asking you, I am telling you. The…'),
(1, 1, 'Well go ahead and tell me. What''s the guy''s name that signs the receipt on first base?'),
(1, 2, 'Well now wait a minute. What signs his own receipt'),
(1, 1, 'Who signs his own receipt?'),
(1, 2, 'No, Who signs his'),
(1, 1, 'I''m askin'' you, when the guy on first base gives you a piece of paper…'),
(1, 2, 'Yes, now wait…'),
(1, 1, '…he puts his name on it'),
(1, 2, 'No, Who puts his name on it…'),
(1, 1, 'How…'),
(1, 2, '…and what puts his name on it…'),
(1, 1, 'How does the fella''s name on first base look to you when he signs his name?'),
(1, 2, 'Who'),
(1, 1, 'To you'),
(1, 2, 'That''s how it does'),
(1, 1, 'How does it look to you?'),
(1, 2, 'Who!'),
(1, 1, 'To you'),
(1, 2, 'Who!'),
(1, 1, 'To you'),
(1, 2, 'Who! Look…'),
(1, 1, 'When the guy signs his name, how does it look to you?'),
(1, 2, 'Now that''s how it looks. Who'),
(1, 1, 'How…Who?'),
(1, 2, 'Who'),
(1, 1, 'I''m askin'' you. What''s the guy''s name on first base you give the money to?'),
(1, 2, 'Who! After all, the man''s entitled to it…'),
(1, 1, 'Who is?'),
(1, 2, 'Yes. Sometimes his wife comes down and collects it'),
(1, 1, 'Whose wife?'),
(1, 2, 'Yeah, sure'),
(1, 1, 'All I''m tryin'' to find out is what''s the guy''s name on first base…'),
(1, 2, 'What is on second base'),
(1, 1, 'I''m not askin'' you who''s on second'),
(1, 2, 'Who''s on first'),
(1, 1, 'I don''t know'),
(1, 2, 'He''s…'),
(1, 1, 'Third base, I know'),
(1, 2, 'Yeah'),
(1, 1, 'You got a outfield?'),
(1, 2, 'Sure'),
(1, 1, 'The left fielder''s name?'),
(1, 2, 'Why'),
(1, 1, 'I just thought I''d ask you'),
(1, 2, 'Well I just thought I''d tell you'),
(1, 1, 'The left fielder''s name?'),
(1, 2, 'Why!?'),
(1, 1, 'Hmm…Because!'),
(1, 2, 'Oh, he''s center field'),
(1, 1, 'Oh…'),
(1, 2, 'Told you all these players got…'),
(1, 1, 'All I''m tryin'' to figure out is what''s the guy''s name in left field'),
(1, 2, 'Now, What''s on second'),
(1, 1, 'I''m not askin'' you who''s on second'),
(1, 2, 'Who''s on first'),
(1, 1, 'I don''t know…'),
(1, 2, 'Third base'),
(1, 1, 'You got a pitcher on this team?'),
(1, 2, 'Wouldn''t be a fine team without a pitcher'),
(1, 1, 'What''s his name?'),
(1, 2, 'Tomorrow'),
(1, 1, 'You don''t want to tell me today?'),
(1, 2, 'I''m telling you'),
(1, 1, 'Then go ahead'),
(1, 2, 'Tomorrow!'),
(1, 1, 'What time?'),
(1, 2, 'What time what?'),
(1, 1, 'What time tomorrow are you gonna tell me who''s pitching?'),
(1, 2, 'Now listen. Who is not…'),
(1, 1, 'I''ll break your arm, you say who''s on first! I want to know what''s the pitcher''s name?'),
(1, 2, 'What''s on second'),
(1, 1, 'I don''t know'),
(1, 1, 'Third base!'),
(1, 1, 'You got a catcher?'),
(1, 2, 'Sure'),
(1, 1, 'The catcher''s name?'),
(1, 2, 'Today'),
(1, 1, 'Today. You don''t wanna tell me, today…tomorrow…do you?'),
(1, 2, 'I''m telling you'),
(1, 1, 'So the catcher''s name?'),
(1, 2, 'Today'),
(1, 1, 'Today. And Tomorrow''s pitching'),
(1, 2, 'Now you''ve got it!'),
(1, 1, 'Now I''ve got it…'),
(1, 2, 'Hey!'),
(1, 1, 'All we got is a couple of days on the team!'),
(1, 2, 'Well I can''t help that'),
(1, 1, 'All right. You know now, I''m a good catcher. Now, I get behind the plate and…and Tomorrow''s pitching on my team and a heavy hitter gets up'),
(1, 2, 'Yes?'),
(1, 1, 'Now when he gets up, me being a good catcher, I''m gonna throw the guy out at first base. So the guy bunts the ball. I pick up the ball, I''m gonna throw the guy out at first base. So I pick up the ball and throw it to who?'),
(1, 2, 'Now that''s the first thing you''ve said right'),
(1, 1, 'I don''t even know what I''m talkin'' about!'),
(1, 2, 'Well that''s…That''s all you have…'),
(1, 1, 'That''s all I have to do is to throw the ball to first base. Now who''s got it?'),
(1, 2, 'Naturally. Now you''ve got it'),
(1, 1, 'I throw the ball to first base, somebody''s gotta get the ball! Now who''s got it?'),
(1, 2, 'Naturally'),
(1, 1, 'Who?'),
(1, 2, 'Naturally'),
(1, 1, 'Naturally?'),
(1, 2, 'Naturally'),
(1, 1, 'So I pick up the ball and I throw it to Naturally'),
(1, 2, 'No, no, no, no…'),
(1, 1, 'He gets the ball. Naturally gets the ball and...'),
(1, 2, 'You throw the ball to first base'),
(1, 1, 'Then who gets it?'),
(1, 2, 'Naturally'),
(1, 1, 'So I pick up the ball and I throw it to Naturally'),
(1, 2, 'No!'),
(1, 1, 'Naturally gets the ball and…and…'),
(1, 2, 'You throw the ball to Who'),
(1, 1, 'Naturally'),
(1, 2, 'Naturally'),
(1, 1, 'That''s what I''m saying!?1'),
(1, 1, 'I said, I throw the ball to Naturally'),
(1, 2, 'No you don''t!'),
(1, 1, 'I throw it to who?'),
(1, 2, 'Naturally'),
(1, 1, 'That''s what I''m saying!'),
(1, 2, 'No it isn''t'),
(1, 1, 'I throw the ball to first base, somebody''s gotta get it'),
(1, 2, 'So Who gets it'),
(1, 1, 'Naturally'),
(1, 2, 'That''s it'),
(1, 1, 'Okay. Now I ask you, who gets it?'),
(1, 2, 'Naturally'),
(1, 1, 'Same as you!'),
(1, 2, 'Now listen…'),
(1, 1, 'I throw the ball to Naturally'),
(1, 2, 'You throw the ball to Who!'),
(1, 1, 'Then who gets it?'),
(1, 2, 'Naturally'),
(1, 1, 'He better get it! So I throw the ball to first base'),
(1, 2, 'All right'),
(1, 1, 'Whoever gets it drops the ball and the guy runs to second. Now, Who picks up the ball and throws it to What. What throws it to I Don''t Know. I Don''t Know throws it back to Tomorrow, triple play'),
(1, 2, 'Could be'),
(1, 1, 'Another guy gets up and hits a long fly ball to Because'),
(1, 2, 'Yes'),
(1, 1, 'Why? I don''t know! He''s on third and I don''t give a darn!'),
(1, 2, 'What''d you say?'),
(1, 1, 'I said, I don''t give a darn!'),
(1, 2, 'Oh, that''s our shortstop!');
